// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict";

var React = require("react");
var ReactDom = require("react-dom");
var Main$ReasonPowerplug = require("./Main.bs.js");

var app = document.querySelector("#app");

if (app == null) {
  console.log("Coudn't find #app element to mount the React app.");
} else {
  ReactDom.render(React.createElement(Main$ReasonPowerplug.make, {}), app);
}

/* app Not a pure module */
